### ISSUE TITLE
Support for R 4.0

### ISSUE THREAD

**Issue by woropajj** [WLOGSolutions/RSuite#12]
I know that with R 4.0 came significant changes to how packages are handled.
Will RSuite support R 4.0 and above?

**Comment by ws171913** [comment]
Yes it will in some time I suppose. We still support it but support for R 4.0 is not priority: all our customers use previous R versions

**Comment by ws171913** [comment]
I realised that all test are passing on R 4.0.1: See travis and appvayer workflows.
So changes in handling packages either are backward compatible or does not influence general apis RSuite uses.
